//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTC.FourthStage.Database.EF.DatabaseFirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSkill
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int JobId { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
