// <auto-generated />
namespace ISTC.FourthStage.Database.DataAnnotation.DA_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Test1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test1));
        
        string IMigrationMetadata.Id
        {
            get { return "201910071625185_Test1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
