// <auto-generated />
namespace ISTC.FourthStage.Database.DataAnnotation.DA_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TypeMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TypeMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201902221618264_TypeMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
