// <auto-generated />
namespace ISTC.FourthStage.Database.EF.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Second : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Second));
        
        string IMigrationMetadata.Id
        {
            get { return "201910050640554_Second"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
