//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTC.FourthStage.Database.LinqToEntity.LinqToEntity_01.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class GithubLinkedinCrossTable
    {
        public int Id { get; set; }
        public int GithubUserId { get; set; }
        public int LinkedinUserId { get; set; }
    }
}
